server:
  port: 9005
spring:
  application:
    name: config-center
  security:
    user:
      name: tao
      password: 123456
  cloud:
    config:
      server:
        git:
          uri: "" #git仓库地址
          username: "" # git 用户名
          password: "" # git 密码
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://tao:123456@localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}
