server:
  port: 8761
spring:
  application:
    name: register-center
  security:
    user:
      name: tao
      password: 123456
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://tao:123456@localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}